char* PID_DESC [] =
{
  "PIDs supported [01 - 20]",
  "Monitor status since DTCs cleared. (Includes malfunction indicator lamp (MIL) status and number of DTCs.)",
  "Freeze DTC",
  "Fuel system status",
  "Calculated engine load",
  "Engine coolant temperature",
  "Short term fuel trim—Bank 1",
  "Long term fuel trim—Bank 1",
  "Short term fuel trim—Bank 2",
  "Long term fuel trim—Bank 2",
  "Fuel pressure (gauge pressure)", ",
  "Intake manifold absolute pressure",
  "Engine RPM",
  "Vehicle speed",
  "Timing advance",
  "Intake air temperature",
  "MAF air flow rate",
  "Throttle position",
  "Commanded secondary air status",
  "Oxygen sensors present (in 2 banks)",
  "Oxygen Sensor 1",
  "Oxygen Sensor 2",
  "Oxygen Sensor 3",
  "Oxygen Sensor 4",
  "Oxygen Sensor 5",
  "Oxygen Sensor 6",
  "Oxygen Sensor 7",
  "Oxygen Sensor 8",
  "OBD standards this vehicle conforms to",
  "Oxygen sensors present (in 4 banks)",
  "Auxiliary input status",
  "Run time since engine start",
  "PIDs supported [21 - 40]",
  "Distance traveled with malfunction indicator lamp (MIL) on",
  "Fuel Rail Pressure (relative to manifold vacuum)",
  "Fuel Rail Gauge Pressure (diesel", or gasoline direct injection)",
  "Oxygen Sensor 1",
  "Oxygen Sensor 2",
  "Oxygen Sensor 3",
  "Oxygen Sensor 4",
  "Oxygen Sensor 5",
  "Oxygen Sensor 6",
  "Oxygen Sensor 7",
  "Oxygen Sensor 8",
  "Commanded EGR",
  "EGR Error",
  "Commanded evaporative purge",
  "Fuel Tank Level Input",
  "Warm-ups since codes cleared",
  "Distance traveled since codes cleared",
  "Evap. System Vapor Pressure",
  "Absolute Barometric Pressure",
  "Oxygen Sensor 1",
  "Oxygen Sensor 2",
  "Oxygen Sensor 3",
  "Oxygen Sensor 4",
  "Oxygen Sensor 5",
  "Oxygen Sensor 6",
  "Oxygen Sensor 7",
  "Oxygen Sensor 8",
  "Catalyst Temperature: Bank 1", Sensor 1",
  "Catalyst Temperature: Bank 2", Sensor 1",
  "Catalyst Temperature: Bank 1", Sensor 2",
  "Catalyst Temperature: Bank 2", Sensor 2",
  "PIDs supported [41 - 60]",
  "Monitor status this drive cycle",
  "Control module voltage",
  "Absolute load value",
  "Fuel–Air commanded equivalence ratio",
  "Relative throttle position",
  "Ambient air temperature",
  "Absolute throttle position B",
  "Absolute throttle position C",
  "Accelerator pedal position D",
  "Accelerator pedal position E",
  "Accelerator pedal position F",
  "Commanded throttle actuator",
  "Time run with MIL on",
  "Time since trouble codes cleared",
  "Maximum value for Fuel–Air equivalence ratio", oxygen sensor voltage", oxygen sensor current", and intake manifold absolute pressure",
  "Maximum value for air flow rate from mass air flow sensor",
  "Fuel Type",
  "Ethanol fuel % ",
  "Absolute Evap system Vapor Pressure",
  "Evap system vapor pressure",
  "Short term secondary oxygen sensor trim", A: bank 1", B : bank 3",
  "Long term secondary oxygen sensor trim", A: bank 1", B : bank 3",
  "Short term secondary oxygen sensor trim", A: bank 2", B : bank 4",
  "Long term secondary oxygen sensor trim", A: bank 2", B : bank 4",
  "Fuel rail absolute pressure",
  "Relative accelerator pedal position",
  "Hybrid battery pack remaining life",
  "Engine oil temperature",
  "Fuel injection timing",
  "Engine fuel rate",
  "Emission requirements to which vehicle is designed",
  "PIDs supported [61 - 80]",
  "Driver's demand engine - percent torque",
  "Actual engine - percent torque",
  "Engine reference torque",
  "Engine percent torque data",
  "Auxiliary input / output supported",
  "Mass air flow sensor",
  "Engine coolant temperature",
  "Intake air temperature sensor",
  "Commanded EGR and EGR Error",
  "Commanded Diesel intake air flow control and relative intake air flow position",
  "Exhaust gas recirculation temperature",
  "Commanded throttle actuator control and relative throttle position",
  "Fuel pressure control system",
  "Injection pressure control system",
  "Turbocharger compressor inlet pressure",
  "Boost pressure control",
  "Variable Geometry turbo (VGT) control",
  "Wastegate control",
  "Exhaust pressure",
  "Turbocharger RPM",
  "Turbocharger temperature",
  "Turbocharger temperature",
  "Charge air cooler temperature (CACT)",
  "Exhaust Gas temperature (EGT) Bank 1",
  "Exhaust Gas temperature (EGT) Bank 2",
  "Diesel particulate filter (DPF)",
  "Diesel particulate filter (DPF)",
  "Diesel Particulate filter (DPF) temperature",
  "NOx NTE (Not-To-Exceed) control area status",
  "PM NTE (Not-To-Exceed) control area status",
  "Engine run time",
  "PIDs supported [81 - A0]",
  "Engine run time for Auxiliary Emissions Control Device(AECD)",
  "Engine run time for Auxiliary Emissions Control Device(AECD)",
  "NOx sensor",
  "Manifold surface temperature",
  "NOx reagent system",
  "Particulate matter (PM) sensor",
  "Intake manifold absolute pressure"
};
